apiVersion: v1
kind: Service
metadata:
  name: cart
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    service: cart


# HELM TEMPLATE COMMAND 
helm template .  ****** this will show us the yaml with their real values .... this helps in future debugging 